#%RAML 1.0

title: Customer recognition API

version: v3.0
mediaType: application/json
uses:
  traits: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-traits/1.1.0/traits.raml
  customer: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/customer-datatypes/1.0.4/customerTypes.raml
  util: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-datatypes/1.0.0/utilTypes.raml
  location: exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-datatypes/1.0.0/locationTypes.raml
types:
  LastFaceDetected:
    properties: 
      lastFaceDetected:
        type: AttachedImageByteArrayID
  AttachedImageByteArrayID:
    properties:
      attachedImageByteArrayID: number
  RecognizedCustomer:
    properties:
      customerRecognized: boolean
      lastFaceDetected: AttachedImageByteArrayID
      name?: string
      image?: string
      lastAvatarID?: number
      newAvatarID?: number
      avartar:
       type: util.ImageData
       required: false
      login?: string
      fullName?: string
      email?: string
      address?: location.AddressData
      gender?: string
      birthday?: date-only
      id?: number
  FaceImageToTest:
    properties:
      imageBase64: string
  CustomerRecognitionResult:
    properties:
      customerRecognized: boolean

/faceCandidates:
  post:
    is: [ traits.secure ]
    description: submit face image to try to be recognized as customer
    body:
      type: FaceImageToTest
      example: 
        imageBase64: ajkhsajdkfhsalfkjahdfalksfhsalkfjhdakjdhfldkjfhds
    responses:
      200:
        body:
          type: CustomerRecognitionResult
          example:
            customerRecognized: false