#%RAML 1.0 NamedExample
id: 612009
type: camping
keywords:
  - camping
  - outdoor
  - florest
  - tent
  - sleeping bag
  - lantern
questions:
  - question: Where are you going?
    id: 1001
  - question: When are you going?
    id: 1002
  - question: How many people on your group?
    id: 1003
  - question: Any kids on the group?
    id: 1004