#%RAML 1.0 NamedExample
outcome_id: 612009
type: camping
answers:
  - question_id: 1001
    answer: Russian River
  - question_id: 1002
    answer: in two weeks
  - question_id: 1003
    answer: three
  - question_id: 1004
    answer: yes, 1 boy