#%RAML 1.0 NamedExample
outcome_id: 612009
type: camping
answers_keywords:
  - id: 2001
    question_id: 1001
    answer: Russian River
  - id: 2002
    question_id: 1002
    answer: in two weeks
  - id: 2003
    question_id: 1003
    answer: three
  - id: 2004
    question_id: 1004
    answer: yes, 1 boy
profile: family outing
categories:
  - description: Sleeping Bags
    recommended_items:
    - id: 7890001
      price: 
        value: 47.95
        currency: USD
      name: Eureka Cypress Sleeping Bag
      description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
      image: 
        id: 8540001
        url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
      link: https://www.opticsplanet.com/eureka-cypress-15-deg-jr-sleeping-bag.html
  - description: Games
    recommended_items:
    - id: 7890010
      name: Mattel UNO Card Game
      description: Easy to pick up...impossible to put down. Play by matching color or number, or play an action card against your opponent. When you're down to one card, don't forget to yell "UNO!" Contains 108 cards and instructions. For 2 to 10 players. Ages 7 and older.
      image:
        id: 8540010
        url: https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRAGd8aVBgzIinWYF-YCl1TCwi1agSVjqIWmA3RSZenW8KOeYQC&usqp=CAY
      price: 
        value: 6.99
        currency: USD
      link: https://www.bestbuy.com/site/mattel-uno-card-game-multi/4189414.p?skuId=4189414&ref=212&loc=1&gclid=CLGLpaWpsdoCFQXefgodwe8BQQ&gclsrc=ds
    - id: 7890014
      name: Wilson Sporting Goods Traditional Soccer Ball Size 4 Synthetic Leather
      description: Synthetic leather cover with shiny finish in a traditional black and white pattern. Superior playability. Butyl bladder for excellent air retention, shape & feel. Official size & weight.
      image:
        id: 8540014
        url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTr-XPLd0DzVWhmg8THgYqfMjHOdFBeqUdkeZ8VCyLB7d4q41_Y9TD6WTr1Ab_0nYR4Wvf1JhwX&usqp=CAY
      price: 
        value: 8.99
        currency: USD
      link: https://www.walmart.com/ip/Wilson-Traditional-Soccer-Ball/9854920?wmlspartner=wlpa&adid=22222222227029515237&wl0=&wl1=g&wl2=c&wl3=49182447512&wl4=pla-71924460414&wl5=9031944&wl6=&wl7=&wl8=&wl9=pla&wl10=8175035&wl11=online&wl12=9854920&wl13=&veh=sem
  - description: Water Bottles
    recommended_items:
    - id: 7890011
      name: 3 Gallon Stackable Water Bottle, Blue
      description: This 3 gallon stackable water bottle is perfect for storing liquid and serving to a large amount of people. Proudly made, it is guaranteed to last a lifetime with its BPA free material and easy-to-grip handle. You'll never have to worry
      image:
        id: 8540011
        url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSgRhse2NtBalWZeWcQmjRlk8QDSAmRaUHxKRH7GtHJzNfaeCsF&usqp=CAY
      price: 
        value: 6.44
        currency: USD
      link: https://www.walmart.com/ip/3-Gallon-Stackable-Water-Bottle/180676866?wmlspartner=wlpa&selectedSellerId=0&adid=22222222227069156862&wmlspartner=wmtlabs&wl0=&wl1=g&wl2=c&wl3=176561934607&wl4=pla-280895208199&wl5=9031944&wl6=&wl7=&wl8=&wl9=pla&wl10=8175035&wl11=online&wl12=180676866&wl13=&veh=sem
  - description: Candies
    recommended_items:
    - id: 7890012
      name: Campfire Mini Marshmallows Packs - White 12-Piece Box
      description: Ancient Egyptians were probably the first people to enjoy the treats we know today as marshmallows. As early as 2000 BCE, Egyptians were squeezing sap from the mallow plant and mixing it with nuts and honey to create a dessert so rare and delicious, it was reserved for royalty. We have no way of knowing what these early marshmallows looked like -- the pillowy shapes with which we are familiar today didn’t originate until the 19th century, when confectioners in France learned how to create a more stable version involving gelatin. Not all marshmallows are created equal. Take these minis, for example -- unlike their bigger brothers, these tiny treats don’t fare well in a campfire. But they still pack a ton of marshmallowy goodness in itty bitty bite-size form! These sweet little things are perfect in hot cocoa, or they make great solo snacks when you’re crave a little surge of yum. And with 90 calories and no fat per pack, they're ideal for a guilt-free nibble!
      image:
        id: 8540012
        url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCHUAWnjyenL7VNfKyjXqyyuSvCdcelRSkhwwQnoVTgXBIhxvWnhU7aH8DSdz4hKz9BZkWQSdT&usqp=CAE
      price: 
        value: 9.00
        currency: USD
      link: https://www.candywarehouse.com/campfire-mini-marshmallows-packs-12-piece-box/?gclid=CjwKCAjwwbHWBRBWEiwAMIV7E6BY_79vtXjPbF1wAhoaoZLEpiQlEncVmUUCTxadAS63x96-1K5g1hoC5lEQAvD_BwE
  - description: Blankets
    recommended_items:
    - id: 7890013
      name: Waterproof Outdoor Blanket Green | L.L.Bean
      description: Don't let a little wet grass ruin your picnic or breakfast at the campsite. This versatile waterproof blanket has a rugged polyurethane-coated nylon backing that keeps moisture from seeping through to the supersoft fleece surface. Top- 100% polyester fleece. Bottom- 100% nylon. Machine wash and dry. Super-soft polyester-fleece surface. Rugged polyurethane-coated nylon backing keeps moisture from seeping through. Great choice for sporting events, the beach on a boat or in your car's safety kit. Stuff sack included.
      image:
        id: 8540013
        url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQCHUAWnjyenL7VNfKyjXqyyuSvCdcelRSkhwwQnoVTgXBIhxvWnhU7aH8DSdz4hKz9BZkWQSdT&usqp=CAE
      price: 
        value: 49.95
        currency: USD
      link: https://www.llbean.com/llb/shop/514485?originalProduct=57230&productId=939399&attrValue_0=Deep%20Forest&pla1=0&mr:device=c&mr:adType=plaonline&qs=3125182_google&lsft=qs:3125182_google,product:0GKD150000&gclid=CjwKCAjwwbHWBRBWEiwAMIV7E9lLzcCOvixfdCqBh0zOHAthdk4AolNsvO7p-OOMf0q9EDDDk2WH1xoC1mIQAvD_BwE&gclsrc=aw.ds&dclid=CNeElqK8sdoCFZJ2Ygodg7AEyA
  - description: Repellents
    recommended_items:
    - id: 7890015
      name: Repel Family Dry Aerosol Insect Repellent, 10% Deet - 4 fl oz spray
      description: Repel Family Dry Aerosol provides hour of protection from mosquitoes and biting flies. Also repel ticks, chiggers, no-see-ums, gnats and fleas. Repel Family Dry Aerosol offers long-lasting protection-- it s not greasy and has no unpleasant odor.
      image:
        id: 8540015
        url: https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRqw24-M_195-JQoMOSSVlWEWjlM5UcJI-DqK2zYWVZHsbTNBdneFQKa_WnjjT2nFmn39X920Mc&usqp=CAY
      price: 
        value: 4.99
        currency: USD
      link: https://www.target.com/p/repel-family-dry-aerosol-4-oz/-/A-14782293?ref=tgt_adv_XS000000&AFID=google_pla_df&CPNG=PLA_Sports+Shopping&adgroup=SC_Sports&LID=700000001170770pgs&network=g&device=c&location=9031944&gclid=CjwKCAjwwbHWBRBWEiwAMIV7E-SMX2Ioi-cdwnxjRMwRIXTyKnLSo9IGInsdYRmZRkOYceTMSKgVoRoCV3EQAvD_BwE&gclsrc=aw.ds
  - description: Campfire Supplies
    recommended_items:
    - id: 7890016
      name: Ignite-O FS855-24 Fire Starter Packets
      description: The Quick, Clean & Easy Way to Start Your Fire! Big flame Burns up to 15 minutes No Fumes; No Residue Just light the packet! The cleaner way to light your fire for fireplaces, wood stoves, charcoal grills and campfires. Contains 20 packets.
      image:
        id: 8540016
        url: https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQuq5gS5UD67LAemZvDEhaE332K8Z3sjlYxr75shbA0Ezl_As8&usqp=CAY
      price: 
        value: 6.99
        currency: USD
      link: http://www.acehardware.com/product/index.jsp?productId=71043076&KPID=22159723&cid=CAPLA:G:Shopping_-_Hearth_Products_&_Accs=&pla=pla_22159723&k_clickid=98dfbd6f-978b-417b-a575-e7467f145b88&gclid=CjwKCAjwwbHWBRBWEiwAMIV7E8En3BcXY2OWQ31IHQEqY3kJo7EcXMzCKW0WAPnyCcwNoqLq0t2AxBoCbiQQAvD_BwE