#%RAML 1.0 NamedExample
locations:
  - id: 7890011
    name: Coleman Sundome 2-Person Tent
    description: "2 person 1 room domed tent. Great for small family solo travelers and first time campers. Easy two pole set up with shock corded 8.5 mm fiberglass poles that slip into continuous pole sleeves. Pin and ring design and instaclip attachments. Durable carry bag with separate storage bags for tents poles and stakes and sewn on instructions. Features: exclusive weatherTec system keeps you dry. Adjustable Variflo ventilation front zip door and vent window interior gear pocket and electrical access port and polyethylene. 1000 D- 140 g/sqm floor."
    price:
      currency: USD
      value: 68.59
    discountedPrice:
      currency: USD
      value: 60.50
    image:
      id: 8540011
      url: https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTAB-NLTn_7HFbw2LhGAUNRosCjv5nvlyEWDjUyBuMlp9Zg5qEScR-EOUdKmh_ueKNA8JCDm2v0&usqp=CAY
  - id: 7890009
    name: Coleman Lantern
    description: Light up your next outdoor gathering with a super-bright lantern! The versatile Premium Powerhouse runs on either Coleman Liquid fuel or unleaded gasoline and uses less fuel than lanterns powered by propane. Delivering an extra-bright 1107 lumens on high, the Coleman Premium Powerhouse Dual Fuel Lantern features an adjustable dimmer knob to allow the perfect amount of light for your campsite, barbecue and more!
    price:
      currency: USD
      value: 89.79
    image:
      id: 8540009
      url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRrT8bmktPPrwX1z974P8DriLGtyegoXAX90JRrStaYCnIwC_g6Nng2gyucVrk8WNAN3TkkfBb2&usqp=CAY
  - id: 7890008
    name: Sintechno Camping Portable Lantern
    description: Sintechno Inc This portable emergency / camp lantern uses 36 white SMD Super Bright LED's which can be recharged by both included solar panel and AC power adapter.
    price:
      currency: USD
      value: 85.99
    image:
      id: 8540008
      url: https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcREYcHVgrBWpAew2bVIrZB4mu7rvhKm-ijxtkSmBvizfVW2NGC--h6jlCX-Gbc7S9rwihlJ7C9D&usqp=CAY
  - id: 7890012
    name: Floureon 42000mAh Portable Power Station Emergency External Battery Pack Generator Backup
    description: AC output is customized according to different countries, areas. a)Please keep the device away from coin, jewelry, keys or other metal object or there will be short circuit hazard. b)Please don't heat this device. Throw the device in the fire, water and other liquid container is not allowed. Please keep the device away from the sun directly. c)Please keep the device away from high humidity and dusty environment d)Please don't crash the device. Open the device privately is not allowed e)Please don't fall down and hard shock on this device. This is normal.
    price:
      currency: USD
      value: 204.74
    image:
      id: 8540012
      url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTwAq4Kn9qdOEMn0aeZkxL5NXEIkp_BPIJ79a6K62Xlz-y0ZRimB5Km18b7rODNyOAF1fmKBBk&usqp=CAE
  - id: 7890003
    name: Goal Zero Yeti 150 Solar Generator External Battery Pack/Power Inverter
    description: Goal Zero Yeti 150 Solar Generator, 22004 A plug-and-play, silent, fume-free generator for emergencies, camping, or wherever you need power. The Goal Zero Yeti 150 Solar Generator is a gas-free source of portable power to keep lights, phones and laptops powered on through any situation.
    price:
      currency: USD
      value: 199.00
    image:
      id: 8540003
      url: https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTqPH1wK0UGXcI55H1rSwKukYH4_AfAU40OH_noVqt4M_E95UTOyZvkdAvMYE_tNfeV-c3Cao8&usqp=CAE  
  - id: 7890002
    name: Goal Zero Lighthouse 400
    description: "This 400-lumen (max. setting) lantern can be charged three ways: from the sun using Goal Zero solar panels (not included), from USB or manually with the hand crank built into the top. Full charge lasts up to 48 hours on the Li-NMC battery."
    price:
      currency: USD
      value: 40.90
    image:
      id: 8540002
      url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTcg1_pBwGoE4XItBXqfhkq8sqCkoBs6ZLKX1JQv9gOxl3M-2vlHF-VX6j-SEMWnOPTuzLQ0VPV&usqp=CAY
  - id: 7890001
    name: Eureka Cypress Sleeping Bag
    description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
    price:
      currency: USD
      value: 47.95
    image:
      id: 8540001
      url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
  - id: 7890014
    name: Wilson Sporting Goods Traditional Soccer Ball Size 4 Synthetic Leather
    description: Synthetic leather cover with shiny finish in a traditional black and white pattern. Superior playability. Butyl bladder for excellent air retention, shape & feel. Official size & weight.
    image:
      id: 8540014
      url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTr-XPLd0DzVWhmg8THgYqfMjHOdFBeqUdkeZ8VCyLB7d4q41_Y9TD6WTr1Ab_0nYR4Wvf1JhwX&usqp=CAY
    price:
      value: 8.99
      currency: USD
fanOn: false
saying: Saying something...
droneDelivered: true
userDetected: true
display: true
shelvesActivated: true
userRecognized: true
