#%RAML 1.0 NamedExample
- id: 5640097
  login: jconnor
  fullName: John Connor
  email: jconnor@gmail.com
  gender: male
  birthday: 1984-03-03
  address: 
    country: USA,
    state: CA,
    city: San Francisco,
    street_address: 77 Geary St #400,
    zip: 94108
  avatar: 
    id: 4321
    url: http://cdn.playbuzz.com/cdn/65e0d76d-1693-468b-841c-7703a7796e36/8958a07c-484d-4da0-8cff-f2fceb55dde8.jpg
- id: 5640098
  login: sconnor
  fullName: Sarah Connor
  email: sconnor@outlook.com
  gender: female
  birthday: 1968-12-15
  address: 
    country: USA
    state: CA
    city: San Francisco
    street_address: 77 Geary St #400
    zip: 94108
  avatar: 
    id: 4322
    url: https://amp.businessinsider.com/images/59c27c3f38d20d2a008b8842-750-563.jpg
- id: 5640099
  login: uri.sarid
  fullName: Uri Sarid
  email: uri.sarid@mulesoft.com
  gender: male
  birthday: 1984-12-14
  address:
    country: USA
    state: CA
    city: San Francisco
    street_address: 77 Geary St #400
    zip: 94108
  avatar:
    id: 4323
    url: https://media.licdn.com/dms/image/C4D03AQHouKvD9PVzLA/profile-displayphoto-shrink_200_200/0?e=1527534000&v=alpha&t=WCl5pwfL9ChyPq_CnjT9SkctwTe9bP_XzC_X9acc_6o