#%RAML 1.0 NamedExample
id: 5640099
login: uri.sarid
fullName: Uri Sarid
email: uri.sarid@mulesoft.com
gender: male
birthday: 1984-12-14
address:
  country: USA
  state: CA
  city: San Francisco
  street_address: 77 Geary St #400
  zip: 94108
avatar:
  id: 4323
  url: https://media.licdn.com/dms/image/C4D03AQHouKvD9PVzLA/profile-displayphoto-shrink_200_200/0?e=1527534000&v=alpha&t=WCl5pwfL9ChyPq_CnjT9SkctwTe9bP_XzC_X9acc_6o