#%RAML 1.0 NamedExample
id: 7890001
price: 
  value: 47.95
  currency: USD
name: Eureka Cypress Sleeping Bag
description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
keywords: [Eureka!,Children's, Mummy, 15° F, With Pocket, With Stuff Sack]
copy: Eureka 15°F Cypress Junior Sleeping Bag - Mummy (for Boys) - Grey/Green ( )
image: 
  id: 8540001
  url: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
company:
  id: 4907999
  name: The-House.com
  address: 
    country: USA
    state: MINNESOTA
    city: Minneapolis
    street_address: 200 S Owasso Blvd E St Paul
    zip: 55117
category: Sleeping Bags
review: 
  reviews: 
    - reviewer_name: Backcountry.com
      review: Just got this in yesterday for our little guy, but he won't get a chance to try it. It's just not packable. Compressed it measures 1'' in diameter and 13'' long. It won't fit in our packs so it's going back. Bummer because the price is really great. I'm sure it would work great for car camping or slumber parties, but if you need to pack look elsewhere.
      date: 2015-06-10
      rate: 2
    - reviewer_name: sunnysports.com
      review: I am 5'2'' and about 100 lbs so I ordered the children's bag. There's still room to grow!! I haven't tested it out yet but I can't wait to try it in my hammock on Mt. Washington!
      date: 2015-06-10
      rate: 4
  averageRate: 3