#%RAML 1.0 NamedExample
id: A2B4
title: Mens Pique Polo Shirt
description: Red, 100% cotton, large men’s t-shirt
link: http://www.example.com/asp/sp.asp?cat=12&id=1030
imageLink: http://www.example.com/image1.jpg
availability: in stock
price:
  value: 15.00
  currency: USD
googleProductCategory: Apparel & Accessories > Clothing > Outerwear > Coats & Jackets
brand: Google
gtin: 3234567890126
mpn: GO12345OOGLE
condition: new
adult: no
multipack: 6
isBundle: true
ageGroup: infant
color: Black
gender: Unisex
material: leather
pattern: striped
sizeType: plus
itemGroupId: AB12345
channel: online
contentLanguage: en_US
offerId: 9999999999999
targetCountry: US