#%RAML 1.0 NamedExample
kind: content#productsListResponse
resources:
  - kind: content#product
    id: A2B4
    title: Mens Pique Polo Shirt
    description: Red, 100% cotton, large men’s t-shirt
    link: http://www.example.com/asp/sp.asp?cat=12&id=1030
    imageLink: http://www.example.com/image1.jpg
    availability: in stock
    price:
      value: 15.00#
      currency: USD
    googleProductCategory: Apparel & Accessories > Clothing > Outerwear > Coats & Jackets
    brand: Google
    gtin: 3234567890126#
    mpn: GO12345OOGLE
    condition: new
    adult: no
    multipack: 6
    isBundle: true
    ageGroup: infant
    color: Black
    gender: Unisex
    material: leather
    pattern: striped
    sizeType: plus
    itemGroupId: AB12345
    channel: online
    contentLanguage: en_US
    offerId: 9999999999999#
    targetCountry: US
  - kind: content#product
    id: online:en-US:US:7890001
    offerId: 7890001#
    title: Eureka 15°F Cypress Junior Sleeping Bag - Mummy (for Boys) - Grey/Green ( )
    description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
    link: http://www.example.com/asp/sp.asp?cat=12&id=1030
    imageLink: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
    contentLanguage: en-US
    targetCountry: US
    channel: online
    ageGroup: infant
    availability: in stock
    brand: Eureka
    color: Green
    condition: new
    gender: unisex
    googleProductCategory: Apparel & Accessories \u003e Clothing \u003e Outerwear \u003e Coats & Jackets
    itemGroupId: ML2018.12345
    material: plastic/polyester
    mpn: Eureka789123
    price:
      value: 47.95#
      currency: USD
    sizes:
      - regular
    sizeSystem: US
    sizeType: regular
    taxes:
      - rate: 1.15
        country: US
        taxShip: true
        locationId: 1014221
    destinations:
      - destinationName: Shopping
        intention: required
