#%RAML 1.0 NamedExample
title: Eureka 15°F Cypress Junior Sleeping Bag - Mummy (for Boys) - Grey/Green ( )
description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
link: http://www.example.com/asp/sp.asp?cat=12&id=1030
imageLink: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
availability: in stock
price:
  value: 47.95
  currency: USD
brand: Eureka
mpn: Eureka789123
condition: new
googleProductCategory: Apparel & Accessories > Clothing > Outerwear > Coats & Jackets
ageGroup: infant
color: Green
gender: Unisex
material: plastic/polyester
sizeSystem: US
sizeType: regular
sizes: regular
itemGroupId: ML2018.12345
channel: online
contentLanguage: en_US
offerId: 7890001
targetCountry: US
taxes:
  country : US
  locationId: 1014221
  rate: 1.15
  taxShip: true