#%RAML 1.0 NamedExample
kind: content#product
id: online:en-US:US:7890001
offerId: 7890001
title: Eureka 15°F Cypress Junior Sleeping Bag - Mummy (for Boys) - Grey/Green ( )
description: Made from the same warm material as the adult size for backpacking and family camping, Eureka's Cyprus Junior is a three-season sleeping bag with toasty ThermaShield insulation that's temperature rated at 15°F. The boy-specific junior size and fit reduces unnecessary weight and bulk while on the trail.
link: http://www.example.com/asp/sp.asp?cat=12&id=1030
imageLink: https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcSzTFAyV9Trgw3J3gmxL0unF0f1JTFmU1YBXsSnhB47xVbxxuBf3WzDerHeqM97Vfg0leKvu0i4&usqp=CAY
contentLanguage: en-US
targetCountry: US
channel: online
ageGroup: infant
availability: in stock
brand: Eureka
color: Green
condition: new
gender: unisex
googleProductCategory: Apparel & Accessories \u003e Clothing \u003e Outerwear \u003e Coats & Jackets
itemGroupId: ML2018.12345
material: plastic/polyester
mpn: Eureka789123
price:
  value: 47.95
  currency: USD
sizes: regular
sizeSystem: US
sizeType: regular
taxes:
  rate: 1.15
  country: US
  taxShip: true
  locationId: 1014221
destinations:
  destinationName: Shopping
  intention: required
