#%RAML 1.0 Library

usage: Dynamic shelf types

uses:
  util: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-datatypes/1.0.0/utilTypes.raml

types:
  Activated:
    properties:
      activated: boolean
  FanControl:
    type: Activated
    properties:
      fanNumber: integer
  Saying:
    properties: 
      text: string
  ShelfStatus:
    properties:
      status:
        enum: [added, removed]
  Item:
    properties:
      id: number
      name: string
      description: string
      price: util.MonetaryAmountData
      discountedPrice?: util.MonetaryAmountData
      image: util.ImageData
  UpdateItem:
    properties:
      itemId: string
      location: number
      change:
        enum: [added, removed]
  ShelvesStatus:
    properties:
      locations: Item[]
      fanOn: boolean
      saying: string
      droneDelivered: boolean
      userDetected: boolean
      display: boolean 
      shelvesActivated: boolean
      userRecognized: boolean
  