#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/987b2d04-16e7-4f28-a2f2-7f9f486b81b8 # 

version: v1
title: product-finder

uses:
  productData: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-datatypes/1.0.9/productTypes.raml

resourceTypes: 
  collection: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/collection.raml  
  collection-item: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/product-finder-resourcetypes/1.0.0/collection-item.raml
  member: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/member.raml

/products:
  type:
    collection:
      response-type: productData.ProductData
      request-type: productData.NewProductData
      response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductCollectionExample.raml
  /{product_id}:
    type:
      member:
        get-response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductExample.raml
        get-response-type: productData.ProductData
        patch-response-type: productData.ProductData