#%RAML 1.0 NamedExample
id: 3345002
products: 
  - id: 7890001
    amount: 2
  - id: 7890002
    amount: 1
  - id: 7890003,
    amount: 1
totalAmountPrice: 199.95
totalAmountPriceCurrency: USD
shippingStatus: non-shipped
customerID: 5640099