#%RAML 1.0 NamedExample
- lastFaceDetected:
    attachedImageByteArrayID: 1123444
  customerRecognized: false
- lastFaceDetected:
    attachedImageByteArrayID: 1123445
  customerRecognized: true
  id: 5640099
  name: Uri
  image: https://pathToUpdatedCustomerImage.io/1123445
  lastAvatarID: 4323
  newAvatarID: 1123445
  login: uri.sarid
  fullName: Uri Sarid
  email: uri.sarid@mulesoft.com
  gender: male
  birthday: 1984-12-14
  address:
    country: USA
    state: CA
    city: San Francisco
    street_address: 77 Geary St #400
    zip: 94108