#%RAML 1.0
version: v3
title: Dynamic Shelf API

uses: 
  shelves: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-datatypes/1.0.11/dynamic_shelf-datatypes.raml
  traits: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-traits/1.1.0/traits.raml

mediaType: application/json

/dynamic_shelf:
  /status:
    get:
      description: retrieve all the items another statuses
      responses:
        200:
          body:
            type: shelves.ShelvesStatus
            example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/shelves_status-example.raml
  /itemUpdates:
    post:
      description: update shelf item
      is: [ traits.secure ]
      body:
        type: shelves.UpdateItem
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/shelf_item-update-example.raml
      responses:
        204:
  /items:
    delete:
      description: Deletes all the items on the shelves.
      is: [ traits.secure ]
      responses:
        200:
  /saying:
    put:
      description:
      is: [ traits.secure ]
      body:
        type: shelves.Saying
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/saying-example.raml
      responses:
        204:
  /fanOn:
    put:
      description:
      is: [ traits.secure ]
      body:
        type: shelves.FanControl
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/fan-control-example.raml
      responses:
        204:
  /droneDelivered:
    put:
      is: [ traits.secure ]
      description:
      body:
        type: shelves.Activated
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml
      responses:
        204:
  /userDetected: 
    put:
      is: [ traits.secure ]
      description:
      body:
        type: shelves.Activated
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml
      responses:
        204:
  /display: 
    put:
      is: [ traits.secure ]
      description:
      body:
        type: shelves.Activated
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml
      responses:
        204:
  /shelvesStatus:
    put:
      is: [ traits.secure ]
      description: |
        Changes the status of lights of the Shelfs
      body:
        type: shelves.Activated
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml
      responses:
        204:
    get:
      description: |
        Retrieve the status of lights of the Shelfs
      responses:
        200:
          body:
            type: shelves.Activated
            example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml

  /userRecognized:
    put:
      is: [ traits.secure ]
      description: |
        Changes the status of recognitin of the user
      body:
        type: shelves.Activated
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml
      responses:
        204:
    get:
      description: |
        Retrieve the status of recognitin of the user
      responses:
        200:
          body:
            type: shelves.Activated
            example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/dynamic_shelf-examples/1.0.11/activated-example.raml