#%RAML 1.0 

title: Catalog API

version: 1.0
mediaType: application/json

uses:
  product: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-datatypes/1.0.10/productTypes.raml
  traits: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-traits/1.0.0/traits.raml

resourceTypes:
  collection: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.3/collection.raml
  member: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.3/member.raml

/catalog:
  /products:
    type:
      collection:
        response-type: product.ProductData
        request-type: product.NewProductData
        response-example:  !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductCollectionExample.raml
    /{product_id}:
      type:
        member:
          get-response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductExample.raml
          get-response-type: product.ProductData
          patch-response-type: product.ProductData
          patch-response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductExample.raml
    /type/{product_type}:
      description: Retrieves all the products from a particular type
      get:
        responses:
          200:
           body:
            application/json:
              type: product.ProductData[]
              example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.17/ProductCollectionExample.raml